// OryCMS Admin — generated by `orycms bootstrap`
// Customize this layout to add nav, auth guards, or theme providers.
import type { Metadata } from "next";
import { AdminProvider } from "./provider";

export const metadata: Metadata = {
  title: "OryCMS Admin",
  robots: { index: false, follow: false },
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AdminProvider>{children}</AdminProvider>;
}
