// OryCMS Admin — generated by `orycms bootstrap`
export default function AdminPage() {
  return (
    <main>
      <h1>OryCMS Admin</h1>
      <p>Your OryCMS admin panel. Configure it in orycms.config.ts.</p>
    </main>
  );
}
