// OryCMS Admin — generated by `orycms bootstrap`
// Add auth context, theme providers, or other client-side wrappers here.
"use client";

export function AdminProvider({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
